### ISSUE TITLE
Upgrade for HDP 2.3

### ISSUE THREAD

**Issue by DhruvKumar** [abajwa-hw/blueprints-view#1]
Has this been validated with HDP 2.3? I tried it on a multi-node 2.3 cluster and the export blueprint failed. It's a great tool, would love to have it work for 2.3

**Comment by DhruvKumar** [comment]
<html>
<head>
<title>Ambari REST API Explorer</title>
<link rel="stylesheet" type="text/css" href="style.css"  />
</head>


<script type="application/json" id="url_list">

[
    {
        "name": "Full cluster blueprint",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster?format=blueprint"
    },
    {
        "name": "Fetch all properties for HDP 2.2 stack",
        "post": "",
        "url": "http://$host/api/v1/stacks/HDP/versions/2.2/services?fields=configurations"
    },        
    {
        "name": "Fetch cluster name",
        "post": "",
        "url": "http://$host/api/v1/clusters"
    },    
    
    {
        "name": "Fetch cluster hosts",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/hosts"
    },         
    {
        "name": "Fetch host details",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/hosts/$hostname"
    }, 
    {
        "name": "Fetch components on a host",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/hosts/$hostname/host_components"
    },             
    {
        "name": "Fetch cluster workflows",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/workflows"
    },        
    {
        "name": "Fetch cluster services",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/services"
    },  
    {
        "name": "HDFS status and service details",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/services/HDFS"
    },
    {
        "name": "HDFS service components",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/services/HDFS/components"
    },    
    {
        "name": "HDFS component Namenode status - full response",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/services/HDFS/components/NAMENODE"
    },
    {
        "name": "HDFS component Namenode status - partial response",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/services/HDFS/components/NAMENODE?fields=metrics/dfs/FSNamesystem/CapacityRemainingGB"
    },    
    {
        "name": "YARN status and service details",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/services/YARN"
    },
    {
        "name": "HBase status and service details",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/services/HBASE"
    },
    {
        "name": "Start HBase service on cluster",
        "post": "{'RequestInfo': {'context' :'Start HBase via REST'}, 'Body': {'ServiceInfo': {'state': 'STARTED'}}}",
        "url": "http://$host/api/v1/clusters/$cluster/services/HBASE"
    },
    {
        "name": "Stop HBase service on cluster",
        "post": "{'RequestInfo': {'context' :'Stop HBase via REST'}, 'Body': {'ServiceInfo': {'state': 'INSTALLED'}}}",
        "url": "http://$host/api/v1/clusters/$cluster/services/HBASE"
    },  
    {
        "name": "List requests/operations",
        "post": "",
        "url": "http://$host/api/v1/clusters/$cluster/requests"
    },    
    {
        "name": "List views",
        "post": "",
        "url": "http://$host/api/v1/views"
    },
    {
        "name": "Find which xml section a property belongs to in HDP 2.2",
        "post": "",
        "url": "http://$host/api/v1/stacks/HDP/versions/2.2/services?configurations/StackConfigurations/property_name=dfs.datanode.failed.volumes.tolerated&fields=configurations/StackConfigurations"
    },
    {
        "name": "WebHDFS",
        "post": "",
        "url": "http://sandbox.hortonworks.com:50070/webhdfs/v1/?op=LISTSTATUS"
    }                
        
]


</script>




<script>


function fetchClusterName(url){
	console.log("fetchClusterName called for: " + url);
    var xmlHttp = new XMLHttpRequest();
    //alert(url);
    xmlHttp.open( "GET", url, false );

    xmlHttp.send( null );
	var clusters = JSON.parse(xmlHttp.responseText);
	var clustername = clusters.items[0].Clusters.cluster_name;
	console.log("detected clustername to be " + clustername);
	return clustername;
}

function updateUrl(){
	console.log("updateURL called");
	var cluster  = document.getElementById('cluster').value.trim();
	var host = document.getElementById('host').value.trim();
	var select = document.getElementById("selectScenario"); 

	var options = JSON.parse(document.getElementById('url_list').innerHTML);			  	
	
	//populate the picklist on first launch  
	if (select.length == 1){			  
		  
		for(var i = 0; i < options.length; i++) {
    		var opt = options[i];
    		var el = document.createElement("option");
    		el.textContent = opt.name;
    		el.value = opt.url;
    		select.appendChild(el);
    	}
 		postinput.value='';
    }

    

 	//parse the hostname:port from document or default to sandbox.hortonworks.com:8080
	var parser = document.createElement('a');
	parser.href = document.URL;
	if (parser.host)
		host = parser.host;    
	else
		host = "sandbox.hortonworks.com:8080";
		
	if (parser.hostname)
		hostname = parser.hostname;    
	
	else {
		hostname = "sandbox.hortonworks.com";	
		console.error("Unable to to detect hostame...using default");	
	}	
	document.getElementById("host").value = host;

    //fetch cluster name by querying API http://host:port/api/v1/clusters or default to Sandbox
    var clusterurl = "http://" + host + "/api/v1/clusters";
    var clustername = fetchClusterName(clusterurl); 
    if (!clustername){
    	console.error("Unable to to detect clustername from: " + clusterurl);
    	clustername = "Sandbox";
    }	
 	 document.getElementById("cluster").value = clustername;   			
        			
    //set the url textbox and post body text box based on user input    			
	if (select.selectedIndex > 0){
		textinput.value = options[select.selectedIndex - 1].url.replace("$host",host).replace("$cluster",cluster).replace("$hostname",hostname); 	
		postinput.value = options[select.selectedIndex - 1].post.replace("$host",host).replace("$cluster",cluster).replace("$hostname",hostname).replace(/'/g,'"'); 
		moveCursorToEnd(textinput);
	}

	//by default only show post field if selected option has post
	if (postinput.value && document.getElementById('postinput').className=='hide'){
		console.log("Expanding post field. postinput val is nonempty"); 
		toggle_textarea('postinput');
	}
	
}

function jsonpResultsCallBack(data)
{
	console.log("jsonpResultsCallBack called");
    //alert(JSON.stringify(data));
}

function Submit()
{
	console.log("Submit called");
    var xmlHttp = null;
	var username  = document.getElementById('username').value.trim();
	var password  = document.getElementById('password').value.trim();
	var url  = document.getElementById('textinput').value.trim();
	var post  = document.getElementById('postinput').value.trim();
	
	var resultArea  = document.getElementById('resultArea');
	resultArea.value = "";

    xmlHttp = new XMLHttpRequest();
    
	//if post text field is not empty, perform PUT
    if (post){
    	console.log("Executing PUT " + url + " with post: " + post);
    	xmlHttp.open( "PUT", url, false );
    	xmlHttp.setRequestHeader('Content-Type', 'application/json');
    	xmlHttp.setRequestHeader("Authorization", "Basic " + btoa(username + ":" + password));
    	xmlHttp.setRequestHeader('X-Requested-By', 'ambari');
    	xmlHttp.send( JSON.stringify(post) );
    }
    /*else if (url.indexOf("xxxxx50070") != -1){
    	console.log("sending Jsonp");
		var s = document.createElement('script');
	    s.id = 'dynScript';
	    s.type='text/javascript';
	    var jsonp_url = url + '?op=LISTSTATUS&callback=jsonpResultsCallBack';
 	    alert("url is " + jsonp_url);
 	    s.src = jsonp_url; 	    
		document.getElementsByTagName('head')[0].appendChild(s);
    }*/
    
	//otherwise perform GET
    else{
    	console.log("Opening GET: " + url);
    	xmlHttp.open( "GET", url, false );

    	xmlHttp.setRequestHeader("Authorization", "Basic " + btoa(username + ":" + password))
    	xmlHttp.send( null );

    }
    //alert(xmlHttp.responseText);

    resultArea.value = xmlHttp.responseText;
    moveCursorToEnd(textinput);
}


function toggle_textarea(objname) {
 	console.log("toggle_textarea called");
 	var selectedobj=document.getElementById(objname);

  	if(selectedobj.className=='hide'){  //check if classname is hide 
  		  selectedobj.style.display = "block";
    	//selectedobj.readOnly=true;
    	selectedobj.className ='show';
  	}else{
    	selectedobj.style.display = "none";
    	selectedobj.className ='hide';
 	}
}

function moveCursorToEnd(input) {
	console.log("moveCursorToEnd called");
	input.focus(); //sets focus to element
	//if (input){
		var val = input.value; //store the value of the element
		input.value = ''; //clear the value of the element
		input.value = val; //set that value back.  
	//}
}

</script>
<body onload="updateUrl()" >

<div align="center" id="credentials" >
	<h1>Ambari REST API Explorer View</h1>
	<label onclick="toggle_textarea('credentialform')" style="cursor:pointer"><u><h2>Show/Hide Cluster details</h2></u></label>

	<form onkeyup="updateUrl()" id="credentialform" style="display:none" class="hide">
  		<h3>Cluster details</h3>
  		<label for="host">
    		<span>Ambari server host:port</span>
    		<input type="text" id="host" size="30" />
  		</label>  

		<label for="cluster">
    		<span>Cluster Name</span>
    		<input type="text" id="cluster"  />
  	  	</label>  
  
  		<label for="username">
    		<span>Username</span>
    		<input type="text" id="username" value="admin" />
  		</label>
		<label for="password" >
    		<span>Password</span>
    		<input type="password" id="password" value="admin"  />
  		</label>
	</form>
</div>

<div align="center" id="request">

	<form id="dropdown" onchange="updateUrl()">

		<label>
    		<span>Either choose a template</span>
  		</label>  
  
  		<select id="selectScenario">
    		<option>Choose a template</option>
  		</select>

  		<label>
    		<span> or enter url below</span>
  		</label>   
		<br>
		<br>
		<p>Ambari REST API details available on <a href='https://github.com/apache/ambari/tree/trunk/ambari-server/docs/api/v1'>git</a>. Blueprint samples/recommended usage available on <a href='https://cwiki.apache.org/confluence/display/AMBARI/Blueprints'>Apache page</a></p>
	</form>

	<form name="myform" action="javascript:Submit()" method="POST">
		<h3>Request Endpoint</h3>
		<input id="textinput" type="text" value="" />
		<br>
		<label onclick="toggle_textarea('postinput')" style="cursor:pointer"><h2><u>Show/Hide Post Body field</u></h2></label>
		<textarea align="center" id="postinput"  style="display:none" class="hide" > </textarea>
		<input type="submit" value="Submit">
		<br>
		<h3>Result</h3>
		<textarea id="resultArea"></textarea>
	</form>
</div>


</body>
</html>

**Comment by abajwa-hw** [comment]
Hey Dhruv I just tried this on a multinode cluster and got it to work. Could you provide more details on the  issue or send me the env details?

**Comment by DhruvKumar** [comment]
Hi Ali - this is a non-issue. I was using the wrong endpoint. Closing it now.

**Comment by DhruvKumar** [comment]
Not sure if I can close it. Can you please mark this as "not an issue"?

**Comment by abajwa-hw** [comment]
Sure
